import Header from '../components/Header.jsx';
import { Link } from 'react-router-dom'; // Import Link for navigation
import Footer from '../components/Footer.jsx';
import './pages.css';
import img02 from '../img/02.jpg';

const News = () => {
  return (
    <>
      <Header />
      {/* <h2 className="heighty">This is a News Page</h2> */}

      {/* news section 01 */}
      <div className='news-01'>
        <h3>
          Today News
        </h3>
        <h4>
          Gucci First - A Vintage Video.
          <br />
          Game Inspired WebGL Experience
        </h4>
      </div>

      <div className='news-02'>
        <img src={img02} alt='image' />
      </div>

      <div className='news-03'>

        <div className='details-03'>
          <h2>Author of the news</h2>
          <h4>Designation</h4>
          <h3>Nov 09, 2024.</h3>
        </div>


        <div className='blogs-03'>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>

          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>

          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>

          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>
          <p>
            hope you having a great time.

            Today, I am going to share a part of the Linkify project with you. This project is one of the best recent projects of our team, which has done branding, 3D, UI\UX, illustration, and ideas generated by our team.
          </p>


        </div>
      </div>


      <Footer />
    </>
  );
};

export default News;
